### ISSUE TITLE
should check the availability of DevModeHandler for prod mode check in LaunchUtil

### ISSUE THREAD

**Issue by haijian-vaadin** [Artur-/a-vaadin-helper#8]
In `LaunchUtil`, it's calling the method from `DevModeHandler` directly, but it could happen that DevModeHandler is not in the classpath, e.g. `vaadin-dev-server` is excluded from the production profile.

Seems sth like below would make it work.

```
try {
    Class.forName("com.vaadin.flow.server.DevModeHandler");
    return DevModeHandler.getDevModeHandler() == null;
} catch (ClassNotFoundException e) {
    return false;
}
```

**Comment by Artur-** [comment]
This has been fixed
